default_language_version:
  python: python3

exclude: "src/migrations/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
      - id: check-added-large-files
      - id: check-illegal-windows-names
      - id: check-case-conflict
      - id: name-tests-test
        args: [--unittest]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: check-vcs-permalinks
      - id: pretty-format-json
        args: [--no-sort-keys]
      - id: debug-statements
      - id: check-docstring-first
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-xml
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-ast
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: https://github.com/python-poetry/poetry
    rev: 2.0.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: local
    hooks:
      - id: coverage-run
        name: coverage-run
        entry: poetry run coverage run
        language: python
        pass_filenames: false
        fail_fast: true
      - id: coverage-report
        name: coverage-report
        entry: poetry run coverage report
        language: python
        pass_filenames: false
        fail_fast: true
